name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://fvvq307sqtk1hndsuoapu4ipj0a4t88odtj45rpgrqtoefimnvkfuif1.qc.dolfincdnx.cn:10443/xdispatchdf9ddd052419f17d/bigota.d.miui.com/V12.5.2.0.QEACNXM/miui_MI8_V12.5.2.0.QEACNXM_f5ec813d1c_10.0.zip?bsreqid=3f727a0a49ad580ff458878561d2dd36
  ROM_NAME: MIUI
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget            
            python -m pip install --upgrade pip
            pip install tensorflow==1.14.0

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
